#!/bin/bash

echo "DNS automatic static setup"

PRIMARY_DNS="1.1.1.1"	#Cloudflare
SECONDARY_DNS="1.0.0.1"

if [[ $EUID -ne 0 ]]; then
	echo "run as root"
	exit 1
fi

# Backup the current resolve.conf
cp /etc/resolv.conf /etc/resolv.conf.bak

# Create a new resolv.conf
echo "# generated by DNS changer script" > /etc/resolv.conf
echo "nameserver $PRIMARY_DNS" >> /etc/resolv.conf
echo "nameserver $SECONDARY_DNS" >> /etc/resolv.conf

